// Mocks generated by Mockito 5.4.6 from annotations
// in monn/test/test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:monn/features/crowdfunding/data/crowdfunding_repository.dart'
    as _i4;
import 'package:monn/features/cryptocurrency/data/cryptocurrency_repository.dart'
    as _i8;
import 'package:monn/features/cryptocurrency/domain/cryptocurrency.dart' as _i9;
import 'package:monn/features/cryptocurrency/domain/cryptocurrency_with_transactions.dart'
    as _i2;
import 'package:monn/features/dashboard/data/savings_repository.dart' as _i6;
import 'package:monn/features/dashboard/domain/savings.dart' as _i7;
import 'package:monn/features/expenses/data/expenses_repository.dart' as _i10;
import 'package:monn/features/life_insurance/data/life_insurance_repository.dart'
    as _i11;
import 'package:monn/features/per/data/per_repository.dart' as _i12;
import 'package:monn/features/reit/data/reit_repository.dart' as _i13;
import 'package:monn/features/reit/domain/reit_with_dividends.dart' as _i14;
import 'package:monn/features/savings_book/data/savings_book_repository.dart'
    as _i15;
import 'package:monn/shared/local/database.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCryptocurrencyWithTransactions_0 extends _i1.SmartFake
    implements _i2.CryptocurrencyWithTransactions {
  _FakeCryptocurrencyWithTransactions_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeBudgetEntry_1 extends _i1.SmartFake implements _i3.BudgetEntry {
  _FakeBudgetEntry_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CrowdfundingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrowdfundingRepository extends _i1.Mock
    implements _i4.CrowdfundingRepository {
  @override
  _i5.Stream<List<_i3.CrowdfundingEntry>> watchCrowdfundings() =>
      (super.noSuchMethod(
            Invocation.method(#watchCrowdfundings, []),
            returnValue: _i5.Stream<List<_i3.CrowdfundingEntry>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<List<_i3.CrowdfundingEntry>>.empty(),
          )
          as _i5.Stream<List<_i3.CrowdfundingEntry>>);

  @override
  _i5.Future<void> editCrowdfunding(
    _i3.CrowdfundingEntriesCompanion? newCrowdfunding,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editCrowdfunding, [newCrowdfunding]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SavingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavingsRepository extends _i1.Mock implements _i6.SavingsRepository {
  @override
  _i5.Stream<List<_i3.SavingsEntry>> watchSavings({
    _i7.SavingsFilter? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchSavings, [], {#filter: filter}),
            returnValue: _i5.Stream<List<_i3.SavingsEntry>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<List<_i3.SavingsEntry>>.empty(),
          )
          as _i5.Stream<List<_i3.SavingsEntry>>);

  @override
  _i5.Future<_i3.SavingsEntry?> getSavings(_i7.SavingsType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getSavings, [type]),
            returnValue: _i5.Future<_i3.SavingsEntry?>.value(),
            returnValueForMissingStub: _i5.Future<_i3.SavingsEntry?>.value(),
          )
          as _i5.Future<_i3.SavingsEntry?>);

  @override
  _i5.Future<void> editSaving(_i3.SavingsEntriesCompanion? newSaving) =>
      (super.noSuchMethod(
            Invocation.method(#editSaving, [newSaving]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [CryptocurrencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCryptocurrencyRepository extends _i1.Mock
    implements _i8.CryptocurrencyRepository {
  @override
  _i5.Stream<List<_i3.CryptocurrencyEntry>> watchCryptocurrencies() =>
      (super.noSuchMethod(
            Invocation.method(#watchCryptocurrencies, []),
            returnValue: _i5.Stream<List<_i3.CryptocurrencyEntry>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<List<_i3.CryptocurrencyEntry>>.empty(),
          )
          as _i5.Stream<List<_i3.CryptocurrencyEntry>>);

  @override
  _i5.Future<_i2.CryptocurrencyWithTransactions> getCryptocurrency(
    _i9.CryptoType? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCryptocurrency, [type]),
            returnValue: _i5.Future<_i2.CryptocurrencyWithTransactions>.value(
              _FakeCryptocurrencyWithTransactions_0(
                this,
                Invocation.method(#getCryptocurrency, [type]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.CryptocurrencyWithTransactions>.value(
                  _FakeCryptocurrencyWithTransactions_0(
                    this,
                    Invocation.method(#getCryptocurrency, [type]),
                  ),
                ),
          )
          as _i5.Future<_i2.CryptocurrencyWithTransactions>);

  @override
  _i5.Future<void> editCryptocurrency({
    required _i3.CryptocurrencyEntriesCompanion? crypto,
    double? transactionAmount,
    DateTime? transactionDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editCryptocurrency, [], {
              #crypto: crypto,
              #transactionAmount: transactionAmount,
              #transactionDate: transactionDate,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ExpensesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpensesRepository extends _i1.Mock
    implements _i10.ExpensesRepository {
  @override
  _i5.Future<_i3.BudgetEntry> getOrCreateBudget() =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateBudget, []),
            returnValue: _i5.Future<_i3.BudgetEntry>.value(
              _FakeBudgetEntry_1(
                this,
                Invocation.method(#getOrCreateBudget, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.BudgetEntry>.value(
              _FakeBudgetEntry_1(
                this,
                Invocation.method(#getOrCreateBudget, []),
              ),
            ),
          )
          as _i5.Future<_i3.BudgetEntry>);

  @override
  _i5.Stream<_i3.BudgetEntry?> watchBudget() =>
      (super.noSuchMethod(
            Invocation.method(#watchBudget, []),
            returnValue: _i5.Stream<_i3.BudgetEntry?>.empty(),
            returnValueForMissingStub: _i5.Stream<_i3.BudgetEntry?>.empty(),
          )
          as _i5.Stream<_i3.BudgetEntry?>);

  @override
  _i5.Future<void> saveBudget(_i3.BudgetEntriesCompanion? budget) =>
      (super.noSuchMethod(
            Invocation.method(#saveBudget, [budget]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [LifeInsuranceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLifeInsuranceRepository extends _i1.Mock
    implements _i11.LifeInsuranceRepository {
  @override
  _i5.Stream<_i3.LifeInsuranceEntry?> watchLifeInsurance() =>
      (super.noSuchMethod(
            Invocation.method(#watchLifeInsurance, []),
            returnValue: _i5.Stream<_i3.LifeInsuranceEntry?>.empty(),
            returnValueForMissingStub:
                _i5.Stream<_i3.LifeInsuranceEntry?>.empty(),
          )
          as _i5.Stream<_i3.LifeInsuranceEntry?>);

  @override
  _i5.Future<void> editLifeInsurance(
    _i3.LifeInsuranceEntriesCompanion? lifeInsurance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editLifeInsurance, [lifeInsurance]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPerRepository extends _i1.Mock implements _i12.PerRepository {
  @override
  _i5.Stream<_i3.PerEntry?> watchPer() =>
      (super.noSuchMethod(
            Invocation.method(#watchPer, []),
            returnValue: _i5.Stream<_i3.PerEntry?>.empty(),
            returnValueForMissingStub: _i5.Stream<_i3.PerEntry?>.empty(),
          )
          as _i5.Stream<_i3.PerEntry?>);

  @override
  _i5.Future<void> editPer(_i3.PerEntriesCompanion? per) =>
      (super.noSuchMethod(
            Invocation.method(#editPer, [per]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ReitRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReitRepository extends _i1.Mock implements _i13.ReitRepository {
  @override
  _i5.Stream<List<_i14.ReitWithDividends>> watchReits() =>
      (super.noSuchMethod(
            Invocation.method(#watchReits, []),
            returnValue: _i5.Stream<List<_i14.ReitWithDividends>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<List<_i14.ReitWithDividends>>.empty(),
          )
          as _i5.Stream<List<_i14.ReitWithDividends>>);

  @override
  _i5.Future<void> addReit(_i3.ReitEntriesCompanion? reit) =>
      (super.noSuchMethod(
            Invocation.method(#addReit, [reit]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addDividend(_i3.ReitDividendEntriesCompanion? dividend) =>
      (super.noSuchMethod(
            Invocation.method(#addDividend, [dividend]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteReit(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReit, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SavingsBookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavingsBookRepository extends _i1.Mock
    implements _i15.SavingsBookRepository {
  @override
  _i5.Stream<List<_i3.SavingsBookEntry>> watchSavingsBooks() =>
      (super.noSuchMethod(
            Invocation.method(#watchSavingsBooks, []),
            returnValue: _i5.Stream<List<_i3.SavingsBookEntry>>.empty(),
            returnValueForMissingStub:
                _i5.Stream<List<_i3.SavingsBookEntry>>.empty(),
          )
          as _i5.Stream<List<_i3.SavingsBookEntry>>);

  @override
  _i5.Future<void> editSavingsBook(
    _i3.SavingsBookEntriesCompanion? savingsBook,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editSavingsBook, [savingsBook]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
