include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - 'lib/**.freezed.dart'
    - 'lib/**.g.dart'
    - 'lib/**.gr.dart'
    - 'lib/**/generated_plugin_registrant.dart'
  errors:
    invalid_annotation_target: ignore
    document_ignores: ignore

linter:
  rules:
    public_member_api_docs: false
