include: package:very_good_analysis/analysis_options.yaml

plugins:
  # riverpod_lint: 3.1.4 // slow down to analyze the dart 🤨

analyzer:
  exclude:
    - "lib/**.freezed.dart"
    - "lib/**.g.dart"
    - "lib/**.gr.dart"
    - "lib/**/generated_plugin_registrant.dart"
    - build/**
    - android/**
    - ios/**
  errors:
    invalid_annotation_target: ignore
    document_ignores: ignore

linter:
  rules:
    public_member_api_docs: false
