global_options:
  drift_dev:not_shared:
    runs_before:
      - riverpod_generator:riverpod_generator

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
      drift_dev:drift_dev:
        enabled: false
      drift_dev:not_shared:
        enabled: true
        generate_for:
          - lib/shared/local/database.dart
