global_options:
  drift_dev:not_shared:
    runs_before:
      - riverpod_generator:riverpod_generator

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
      drift_dev:drift_dev:
        enabled: false
      drift_dev:not_shared:
        enabled: true
        options:
          databases:
            app_database: lib/shared/local/database.dart
          schema_dir: drift_schemas/
          test_dir: test/drift/
        generate_for:
          - lib/shared/local/database.dart
