// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    savingsEntries,
    cashEntries,
    crowdfundingEntries,
    savingsBookEntries,
    counterStrikeEntries,
    peaEntries,
    perEntries,
    lifeInsuranceEntries,
    freelanceEntries,
    budgetEntries,
    cryptocurrencyEntries,
    cryptocurrencyTransactionEntries,
    reitEntries,
    reitDividendEntries,
    cryptocurrencyTransactionCryptoDate,
    reitDividendReit,
  ];
  late final Shape0 savingsEntries = Shape0(
    source: i0.VersionedTable(
      entityName: 'savings_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(type)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 cashEntries = Shape1(
    source: i0.VersionedTable(
      entityName: 'cash_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 crowdfundingEntries = Shape2(
    source: i0.VersionedTable(
      entityName: 'crowdfunding_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 savingsBookEntries = Shape3(
    source: i0.VersionedTable(
      entityName: 'savings_book_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_11, _column_12, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 counterStrikeEntries = Shape4(
    source: i0.VersionedTable(
      entityName: 'counter_strike_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 peaEntries = Shape5(
    source: i0.VersionedTable(
      entityName: 'pea_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_22, _column_23, _column_24, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 perEntries = Shape6(
    source: i0.VersionedTable(
      entityName: 'per_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_26, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 lifeInsuranceEntries = Shape6(
    source: i0.VersionedTable(
      entityName: 'life_insurance_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_26, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 freelanceEntries = Shape7(
    source: i0.VersionedTable(
      entityName: 'freelance_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 budgetEntries = Shape8(
    source: i0.VersionedTable(
      entityName: 'budget_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 cryptocurrencyEntries = Shape9(
    source: i0.VersionedTable(
      entityName: 'cryptocurrency_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(type)'],
      columns: [_column_0, _column_1, _column_41, _column_42, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 cryptocurrencyTransactionEntries = Shape10(
    source: i0.VersionedTable(
      entityName: 'cryptocurrency_transaction_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_43, _column_44, _column_45],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 reitEntries = Shape11(
    source: i0.VersionedTable(
      entityName: 'reit_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_11, _column_46, _column_47, _column_48],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 reitDividendEntries = Shape12(
    source: i0.VersionedTable(
      entityName: 'reit_dividend_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_49, _column_10, _column_45],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index cryptocurrencyTransactionCryptoDate = i1.Index(
    'cryptocurrency_transaction_crypto_date',
    'CREATE INDEX cryptocurrency_transaction_crypto_date ON cryptocurrency_transaction_entries (cryptocurrency_id, date)',
  );
  final i1.Index reitDividendReit = i1.Index(
    'reit_dividend_reit',
    'CREATE INDEX reit_dividend_reit ON reit_dividend_entries (reit_id)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get startAmount =>
      columnsByName['start_amount']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'PRIMARY KEY AUTOINCREMENT',
      ),
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_2(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'start_amount',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get label =>
      columnsByName['label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get value =>
      columnsByName['value']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'label',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_4(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get brutProfit =>
      columnsByName['brut_profit']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get platformName =>
      columnsByName['platform_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get netProfit =>
      columnsByName['net_profit']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get taxProfit =>
      columnsByName['tax_profit']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get taxPercentage =>
      columnsByName['tax_percentage']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get receivedAt =>
      columnsByName['received_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<double> _column_5(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'brut_profit',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'platform_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_7(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'net_profit',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_8(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'tax_profit',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_9(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'tax_percentage',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<DateTime> _column_10(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'received_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get startAmount =>
      columnsByName['start_amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get withdrawal =>
      columnsByName['withdrawal']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get interests =>
      columnsByName['interests']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_12(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'start_amount',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_13(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'withdrawal',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_14(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'interests',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get boughtAt =>
      columnsByName['bought_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastUpdate =>
      columnsByName['last_update']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get imageId =>
      columnsByName['image_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get purchaseValue =>
      columnsByName['purchase_value']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get currentValue =>
      columnsByName['current_value']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get wear =>
      columnsByName['wear']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<DateTime> _column_15(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'bought_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<DateTime> _column_16(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'last_update',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'image_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_18(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'purchase_value',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_19(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'current_value',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quantity',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<double> _column_21(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'wear',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get equity =>
      columnsByName['equity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get costAverage =>
      columnsByName['cost_average']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lastPrice =>
      columnsByName['last_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get lastUpdate =>
      columnsByName['last_update']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'equity',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<double> _column_23(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'cost_average',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_24(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'last_price',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<DateTime> _column_25(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'last_update',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get invested =>
      columnsByName['invested']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get interests =>
      columnsByName['interests']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<double> _column_26(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'invested',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get annualRevenue =>
      columnsByName['annual_revenue']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<double> _column_27(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'annual_revenue',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get freelanceIncome =>
      columnsByName['freelance_income']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get rent =>
      columnsByName['rent']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get electricity =>
      columnsByName['electricity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get gas =>
      columnsByName['gas']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get water =>
      columnsByName['water']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get internet =>
      columnsByName['internet']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get homeInsurance =>
      columnsByName['home_insurance']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get publicTransport =>
      columnsByName['public_transport']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get groceries =>
      columnsByName['groceries']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get restaurants =>
      columnsByName['restaurants']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get healthInsurance =>
      columnsByName['health_insurance']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get phone =>
      columnsByName['phone']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get ai =>
      columnsByName['ai']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<double> _column_28(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'freelance_income',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_29(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'rent',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_30(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'electricity',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'gas',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_32(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'water',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_33(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'internet',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_34(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'home_insurance',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_35(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'public_transport',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_36(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'groceries',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_37(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'restaurants',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'health_insurance',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_39(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'phone',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_40(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'ai',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get totalCrypto =>
      columnsByName['total_crypto']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get priceMarket =>
      columnsByName['price_market']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get lastUpdate =>
      columnsByName['last_update']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<double> _column_41(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_crypto',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );
i1.GeneratedColumn<double> _column_42(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'price_market',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      defaultValue: const CustomExpression('0.0'),
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cryptocurrencyId =>
      columnsByName['cryptocurrency_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get date =>
      columnsByName['date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cryptocurrency_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES cryptocurrency_entries (id) ON DELETE CASCADE',
      ),
    );
i1.GeneratedColumn<DateTime> _column_44(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<double> _column_45(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'amount',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get boughtOn =>
      columnsByName['bought_on']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get shares =>
      columnsByName['shares']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get price =>
      columnsByName['price']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<DateTime> _column_46(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'bought_on',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'shares',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<double> _column_48(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'price',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reitId =>
      columnsByName['reit_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get receivedAt =>
      columnsByName['received_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reit_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES reit_entries (id) ON DELETE CASCADE',
      ),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
